[[redirects]]
  from = "http://bytesitedigital.com.au/*"
  to = "https://bytesitedigital.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.bytesitedigital.com.au/*"
  to = "https://bytesitedigital.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bytesitedigital.com.au/*"
  to = "https://bytesitedigital.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  methods = ["GET", "HEAD"]